### ISSUE TITLE
[BUG] Simulator Crash Causes Plants to Die from no water

### ISSUE THREAD

**Issue by IAmNolanPerry** [SatyrFarm/SatyrFarm#11] opened 2018-08-22 22:05 UTC
**Describe the bug**
If a opensimulator simulator server crashes, when it restarts, all of the plants think they didnt get any water, so they die

**To Reproduce**
Crash the Simulator, and Reboot

**Expected behavior**
?

**Comment by IAmNolanPerry** [comment] 2018-08-26 00:40
@opensimworld Will this be fixed or should i mark this as "wont fix"?

**Comment by opensimworld** [comment] 2018-08-27 07:47
This will happen if the simulator resets all scripts after restarting. It's not a bug specific to SF but an opensim problem. We may provide a remedy in the future though (save the state of the plant in a notecard and restore on script reset) . The storage boxes do that already.

It's a feature request, really.

**Comment by opensimworld** [comment] 2018-08-27 07:48
If they died from no watering instead, then the server must have been down for many hours. It's kind of normal behaviour though.

Thinking of it , how do plants work in kitely? if they work at all??

**Comment by uriesk** [comment] 2018-08-28 13:54
I am currently reworking the plant script, i will fix it.

Plants Die from No Water if the Sim is longer offline as the 1.5 times the watering time, i would rather prefer it if the plants are on "pause" and don't do anything as long as it's offline (animals behave like that too).

Surviving a Script Reset would be nice too, but that should better be optional.

**Comment by uriesk** [comment] 2018-08-28 16:12
should be fixed

**Comment by IAmNolanPerry** [comment] 2018-08-28 16:19
Related to Commit b50469a9c3fbac1c47eb428a6709f1de2f636e11

**Closed as completed** 2018-08-28 16:20 UTC
Labels: bug
